version: '3'

services:
  mongodb:
    image: mongo
    container_name: my-mongodb-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: stuyTownistas

  flask-app:
    build:
      context: ./web-app
    container_name: my-flask-app-container
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/stuyTownistas"

  ml-app:
    build:
      context: ./machine-learning-client
    container_name: my-ml-app-container
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017/stuyTownistas"
